---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
  labels:
    app: kubevirt

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: community-kubevirt-hyperconverged
  namespace: kubevirt

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: community-kubevirt-hyperconverged
  namespace: kubevirt
spec:
  channel: stable
  name: community-kubevirt-hyperconverged
  source: operatorhubio-catalog
  sourceNamespace: olm

---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - HostDisk
  imagePullPolicy: IfNotPresent
