---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dbsvr
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: dbsvr
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          rng: {}
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 1Gi
            cpu: "1"
      terminationGracePeriodSeconds: 0
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              qemuGuestAgent:
                users:
                  - evan
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:44
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: evan
              password: dbsvr
              chpasswd: { expire: False }
              # Disable SELinux for now, so qemu-guest-agent can write the authorized_keys file
              # The selinux-policy is too restrictive currently, see open bugs:
              #   - https://bugzilla.redhat.com/show_bug.cgi?id=1917024
              #   - https://bugzilla.redhat.com/show_bug.cgi?id=2028762
              #   - https://bugzilla.redhat.com/show_bug.cgi?id=2057310
              bootcmd:
                - setenforce 0
