---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 1Gi
            cpu: "1"
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              qemuGuestAgent:
                users:
                  - evan
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:26.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: evan
              password: bastion
              chpasswd: { expire: False }
              ssh_pwauth: True
