---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guacd
  namespace: guacd
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: websecure
  #   traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`guac.apps.lab.lan`)
      kind: Rule
      services:
        - name: guacd
          port: 8080
